{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "articulate.serviceAccountName" . }}
  labels:
{{ include "articulate.labels" . | nindent 4 }}
{{- end -}}
